"""add documents table

Revision ID: 7d8e7b1b681e
Revises: f3a9c1d2e4b5
Create Date: 2026-09-07 02:00:56.714196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d8e7b1b681e'
down_revision: Union[str, None] = 'f3a9c1d2e4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.String(length=128), nullable=False),
    sa.Column('doc_type', sa.String(length=50), server_default='general', nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('content_type', sa.String(length=255), server_default='application/octet-stream', nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_patient_id'), 'documents', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_patient_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
